name: 2b2tTakeoffCommand
author: MangosteenLmao
version: 1.0-SNAPSHOT
main: me.MangosteenLmao.TakeoffCommand.TakeoffCommand
description: eases elytra takeoff
commands:
   takeoff:
      description: teleports the player three blocks up. It only works if the player has an elytra, is standing on the ground, and has air above them.