name: 2b2tTakeoffCommand
author: MangosteenLmao
version: 1.0-SNAPSHOT
main: me.MangosteenLmao.TakeoffCommand.TakeoffCommand
description: eases elytra takeoff
commands:
   takeoff:
      description: teleports the player three blocks up. Need: elytra, air above, and to be standing on a block.
